// app-nuxtjs-3-starter/components/Stories.vue
<script lang="ts" setup>
import { Story } from '~/src/Story'
defineProps<{
  stories: Story[]
}>()
</script>
<template>
  <ul>
    <li
      v-for="story in stories"
      :key="story.id"
    >
      {{ story.is_folder ? '📁' : '📄' }} <strong>{{ story.name }}</strong>
    </li>
  </ul>
</template>
<style></style>

// app-nextjs-starter/src/components/Stories.tsx
import {FunctionComponent} from "react";
import styles from './Stories.module.css'
import {Story} from "@src/Story";

export const Stories: FunctionComponent<{
  stories: Story[]
}> = (props) => (
  <ul className={styles.list}>
    {props.stories.map(story => (
      <li key={story.id} className={styles.listItem}>
        {story.is_folder ? '📁' : '📄'} <strong>{story.name}</strong>
      </li>
    ))}
  </ul>
)
