// app-nuxtjs-3-starter/pages/401.vue
<script setup lang="ts">
onMounted(() => {
  if (typeof window !== 'undefined' && window.top === window.self) {
    window.location.assign('https://app.storyblok.com/oauth/app_redirect')
  }
})
</script>

<template>
  <div class="error">
    <UnauthorizedIcon />
    <h3 class="error__title">Unauthorized</h3>
    <h4 class="error_subtitle">Failed to authenticate</h4>
  </div>
</template>

<style scoped>
.error {
  width: 100%;
  background-color: #f5f5f5;
  border-radius: 10px;
  flex-direction: column;
  display: flex;
  align-items: center;
  justify-content: center;
}

.error__title {
  margin: 10px 0;
  font-weight: 700;
  letter-spacing: 0;
  font-size: 1.625rem;
  line-height: 1.167;
}

.error_subtitle {
  margin: 0;
  font-weight: 400;
  letter-spacing: 0.00938em;
  color: #8d919f;
}
</style>

// app-nextjs-starter/pages/401.tsx
import { NextPage } from 'next'
import { useEffect } from 'react'
import { Layout } from '@src/components/Layout'
import { UnauthorizedIcon } from '@src/components/UnauthorizedIcon'
import styles from '@src/styles/401.module.css'

const Page: NextPage = () => {
  useEffect(() => {
    if (typeof window !== 'undefined' && window.top === window.self) {
      window.location.assign('https://app.storyblok.com/oauth/app_redirect')
    }
  }, [])

  return (
    <Layout>
      <article className={styles.error}>
        <UnauthorizedIcon />
        <h3 className={styles.error__title}>Unauthorized</h3>
        <h4 className={styles.error_subtitle}>Failed to authenticate</h4>
      </article>{' '}
    </Layout>
  )
}

export default Page
