// app-nextjs-starter/src/components/Stories.tsx
import {FunctionComponent} from "react";
import styles from './Stories.module.css'
import {Story} from "@src/Story";

export const Stories: FunctionComponent<{
  stories: Story[]
}> = (props) => (
  <ul className={styles.list}>
    {props.stories.map(story => (
      <li key={story.id} className={styles.listItem}>
        {story.is_folder ? '📁' : '📄'} <strong>{story.name}</strong>
      </li>
    ))}
  </ul>
)

// app-nuxtjs-starter/components/Stories.vue
<template>
    <ul class="list">
        <li v-for="story in stories" :key="story.uid">
            {{story.is_folder ? '📁' : '📄'}} <strong>{{story.name}}</strong>
        </li>
    </ul>
</template>

<script>
export default {
  name: 'Stories',
  props: {
    stories: [Array],
  },
}
</script>

<style scoped>
.list {
  padding: 0;
  list-style: none;
}

.listItem {
  padding: 10px 15px;
  display: flex;
  gap: 10px;
}
</style>
